Repository MichenaudMelvin/Glitch, pull requests merged in 2023-06, with the labels that each got.

#239 FX Gold
  GlitchUE/Content/VFX/Particles/FX_Avatar/Pk_Charge.uasset
  GlitchUE/Content/VFX/Particles/FX_Environment/Pk_FeuFollet.uasset
  GlitchUE/Content/VFX/Particles/FX_Environment/Pk_GoldGeneration.uasset
  GlitchUE/Content/VFX/Particles/FX_Environment/Pk_LianesMED.uasset
  GlitchUE/Content/VFX/Particles/FX_Environment/Pk_LianesTECH.uasset
  GlitchUE/Content/VFX/Particles/FX_Towers/Pk_CristalAugment.uasset
  GlitchUE/Content/VFX/Particles/Meshes/SM_GoldIngot.uasset
  GlitchUE/Content/VFX/Particles/Meshes/SM_MED_Grip_Leaves.uasset
  GlitchUE/Content/VFX/Particles/Meshes/SM_TECH_Grip_Leaves.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_CircleSound.uasset
Labels: Bug fix, Art

#252 FIX FXs
  GlitchUE/Content/VFX/Particles/FX_Enemies/Drones/Pk_AttackingDrone_Attack.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Pk_BurningStatus.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Pk_FearedStatus.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Pk_FrozenStatus.uasset
  GlitchUE/Content/VFX/Particles/FX_Environment/Pk_FeuFollet.uasset
  GlitchUE/Content/VFX/Particles/FX_Environment/Pk_Unlocking.uasset
Labels: Bug fix, Art

#261 Balancing value for Tower Defense
  GlitchUE/Content/Blueprint/AI/AIPatrol/DA_PatrolData.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/DA_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/DA_FocusHeavy.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/DA_FocusLight.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/DA_FocusMedium.uasset
  GlitchUE/Content/Blueprint/GlitchZone/BP_GlitchZone.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_FireTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_IceTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_PoisonTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_WindTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Crossbow.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Mortar.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_RailGun.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Wizard.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Content/Blueprint/Player/Gamemodes/BP_TutorialGamemode.uasset
  GlitchUE/Content/FMOD/Desktop/SFX.bank
  GlitchUE/Source/GlitchUE/Private/Audio/AudioManager.cpp
Labels: Update, Game design

#262 New UI features
  GlitchUE/Config/DefaultGame.ini
  GlitchUE/Content/Blueprint/AI/AIPatrol/BT_Patrol.uasset
  GlitchUE/Content/Blueprint/Menu/MainMenu/WBP_Introduction.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Content/Blueprint/Rebords/BP_Edge.uasset
  GlitchUE/Content/Blueprint/UI/CustomElements/WBP_CustomSlider.uasset
  GlitchUE/Content/Blueprint/UI/Gameplay/WBP_DisplayStats.uasset
  GlitchUE/Content/Blueprint/UI/Gameplay/WBP_TimerWidget.uasset
  GlitchUE/Content/Blueprint/UI/Gameplay/WheelAndHotBar/WBP_Wheel.uasset
  GlitchUE/Content/Blueprint/UI/Menu/Settings/WBP_AudioSettings.uasset
  GlitchUE/Content/Blueprint/UI/Menu/Settings/WBP_GameplaySettings.uasset
  GlitchUE/Content/Blueprint/UI/Menu/Settings/WBP_SettingContainer.uasset
  GlitchUE/Content/Blueprint/UI/Menu/Settings/WBP_VideoSettings.uasset
  GlitchUE/Content/UI/Fonts/FF_NumberFont.uasset
  GlitchUE/Content/UI/Introduction/T_Introp_ESMA.uasset
  GlitchUE/Content/UI/Introduction/T_Introp_Unreal.uasset
  GlitchUE/Content/UI/Introduction/T_Introp_warning.uasset
  GlitchUE/Content/UI/Introduction/T_LogoESMA.uasset
  GlitchUE/Content/UI/Introduction/T_LogoUE.uasset
  GlitchUE/Content/UI/Menu/T_ArrowDown.uasset
  GlitchUE/Content/UI/Menu/T_ComboBoxButton.uasset
  GlitchUE/Content/UI/Menu/T_ComboBoxButtonHovered.uasset
  GlitchUE/Content/UI/Menu/T_ScrollBar.uasset
  GlitchUE/Content/UI/Settings/T_BlocSettings.uasset
  GlitchUE/Content/UI/Settings/T_BoolFalse.uasset
  GlitchUE/Content/UI/Settings/T_BoolTrue.uasset
  GlitchUE/Content/UI/Settings/T_BoolTrueHover.uasset
  GlitchUE/Content/UI/Settings/T_ContainerList.uasset
  GlitchUE/Content/UI/Settings/T_DownArrow.uasset
  GlitchUE/Content/UI/Settings/T_Slider.uasset
  GlitchUE/Content/UI/Settings/T_SliderBar.uasset
  GlitchUE/Content/UI/Settings/T_SliderBase.uasset
  GlitchUE/Source/GlitchUE/Private/AI/GeneralTasks/MakeLooseTime.cpp
  GlitchUE/Source/GlitchUE/Private/AI/GeneralTasks/PlayFMODSound.cpp
  GlitchUE/Source/GlitchUE/Private/Gamemodes/GlitchUEGameMode.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayerController.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Custom/CustomButton.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Custom/CustomComboBoxString.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Gameplay/PlacableSelection/PlacableObjectButton.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Gameplay/PlacableSelection/Wheel.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Gameplay/PlayerStats.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Gameplay/Tchat/Tchat.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Gameplay/TimerWidget.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Menu/Settings/SettingsContainerMenu.cpp
  GlitchUE/Source/GlitchUE/Public/AI/GeneralTasks/MakeLooseTime.h
  GlitchUE/Source/GlitchUE/Public/AI/GeneralTasks/PlayFMODSound.h
  GlitchUE/Source/GlitchUE/Public/Gamemodes/GlitchUEGameMode.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
  GlitchUE/Source/GlitchUE/Public/UI/Custom/CustomButton.h
  GlitchUE/Source/GlitchUE/Public/UI/Custom/CustomComboBoxString.h
  GlitchUE/Source/GlitchUE/Public/UI/Gameplay/PlacableSelection/PlacableObjectButton.h
  GlitchUE/Source/GlitchUE/Public/UI/Gameplay/PlacableSelection/Wheel.h
  GlitchUE/Source/GlitchUE/Public/UI/Gameplay/PlayerStats.h
  GlitchUE/Source/GlitchUE/Public/UI/Gameplay/TimerWidget.h
  GlitchUE/Source/GlitchUE/Public/UI/Menu/Settings/VideoSettingsMenu.h
Labels: Bug fix, New Feature, Update, Programmation

#263 FIX: FX Drone Surveillance
  GlitchUE/Content/Blueprint/LevelElement/DT_Props.uasset
  GlitchUE/Content/Meshs/Props/Furniture/SM_TECH_Armoire.uasset
  GlitchUE/Content/Meshs/Props/Furniture/SM_TECH_Autel.uasset
  GlitchUE/Content/Meshs/Props/Furniture/SM_TECH_Box.uasset
  GlitchUE/Content/Meshs/Props/Furniture/SM_TECH_Buffet.uasset
  GlitchUE/Content/Meshs/Props/Furniture/SM_TECH_SculptHead.uasset
  GlitchUE/Content/Meshs/Props/Kitchen/SM_TECH_MeatLeg.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Drones/Pk_DroneAttackV1_Death.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Drones/Pk_DroneAttackV2_Death.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Drones/Pk_DroneAttackV3_Death.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Pk_DroneSpotted.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Pk_EnemyDeath.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_LightningSurveillance.uasset
Labels: Bug fix, Art

#270 KeyboardMesh
  GlitchUE/Content/Meshs/Narrative_Ressources/SM_TECH_Keyboard.uasset
Labels: New Feature, Art

#275 FIX: FX mortar & spotted
  GlitchUE/Content/VFX/Particles/FX_Enemies/Pk_DroneSpotted.uasset
  GlitchUE/Content/VFX/Particles/FX_Towers/FX_Mortar/Pk_MortarExplosion.uasset
Labels: Bug fix, Update, Art

#277 Fix statue mesh
  GlitchUE/Content/Meshs/Props/Furniture/SM_HeadSculpt.uasset
Labels: Bug fix, Update, Art

#280 Packages fix
  GlitchUE/Config/DefaultInput.ini
  GlitchUE/Content/Animation/Level_Sequence/LS_TUTO_Gold_Emplacement.uasset
  GlitchUE/Content/Animation/Player/AS_Crouch.uasset
  GlitchUE/Content/Animation/Player/AS_Jog.uasset
  GlitchUE/Content/Animation/Player/AS_Run.uasset
  GlitchUE/Content/Blueprint/AI/AISpawner/BP_Spawner.uasset
  GlitchUE/Content/Blueprint/LevelElement/LightElements/BP_LightElement_Chandelier.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Content/Blueprint/Player/Gamemodes/BP_MainGamemode.uasset
  GlitchUE/Content/Blueprint/Player/Gamemodes/BP_TransitionGamemode.uasset
  GlitchUE/Content/Blueprint/Player/Gamemodes/BP_TutorialGamemode.uasset
  GlitchUE/Content/Blueprint/UI/Gameplay/WBP_CreditScreen.uasset
  GlitchUE/Content/Blueprint/UI/Gameplay/WBP_DisplayStats.uasset
  GlitchUE/Content/Blueprint/UI/Gameplay/WBP_PopUp.uasset
  GlitchUE/Content/Blueprint/UI/Gameplay/WheelAndHotBar/WBP_Wheel.uasset
  GlitchUE/Content/Maps/Main_Menu.umap
  GlitchUE/Content/Maps/Playable-Level/LVL-Infiltration.umap
  GlitchUE/Content/Maps/Playable-Level/LVL-TWD.umap
  GlitchUE/Content/Meshs/Compass/SM_SpawnerPointer.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_SpawnerPointer.uasset
  GlitchUE/Content/UI/Fonts/FF_Text.uasset
  GlitchUE/Content/UI/Fonts/FONT_Text.uasset
  GlitchUE/Content/UI/Wheel/T_WheelTextBlock.uasset
  GlitchUE/Content/VFX/Particles/FX_Avatar/Pk_SoundDetection.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolCharacter.cpp
  GlitchUE/Source/GlitchUE/Private/AI/MainAICharacter.cpp
  GlitchUE/Source/GlitchUE/Private/Components/SightComponent.cpp
  GlitchUE/Source/GlitchUE/Private/Gamemodes/GlitchUEGameMode.cpp
  GlitchUE/Source/GlitchUE/Public/Components/SightComponent.h
  GlitchUE/Source/GlitchUE/Public/Gamemodes/GlitchUEGameMode.h
Labels: Bug fix, New Feature, Update, Programmation

#281 Steps gain change
  GlitchUE/Content/FMOD/Desktop/SFX.bank
Labels: Update, Audio

#282 Balanced
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/DA_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/Objectives/BP_Catalyseur.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Mortar.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_RailGun.uasset
Labels: Update, Game design

#283 Light fix + door missing mesh + tchat open fix
  GlitchUE/Content/Animation/Level_Sequence/LS_TUTO_GlitchDash.uasset
  GlitchUE/Content/Blueprint/AI/AISpawner/DT_Waves.uasset
  GlitchUE/Content/Blueprint/LevelElement/LightElements/BP_LightElement.uasset
  GlitchUE/Content/Blueprint/LevelElement/LightElements/BP_Lustre.uasset
  GlitchUE/Content/Blueprint/Player/Gamemodes/BP_TutorialGamemode.uasset
  GlitchUE/Content/Blueprint/UI/Gameplay/Tchat/WBP_Tchat.uasset
  GlitchUE/Content/Maps/Onboarding/Sequence.umap
  GlitchUE/Content/Maps/Playable-Level/LVL-Infiltration.umap
  GlitchUE/Content/Maps/Playable-Level/LVL-Moving-Sequence.umap
  GlitchUE/Content/Meshs/ModuilarKit/Door/SM_Up_Door_Frame_6.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolCharacter.cpp
  GlitchUE/Source/GlitchUE/Private/LevelElements/BasicDoor.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayerController.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Gameplay/Tchat/Tchat.cpp
  GlitchUE/Source/GlitchUE/Public/LevelElements/BasicDoor.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayerController.h
Labels: Bug fix, New Feature, Update, Programmation

#285 Fix FX Mortar
  GlitchUE/Content/VFX/Particles/FX_Towers/FX_Mortar/Pk_MortarExplosion.uasset
Labels: Bug fix, Art
