Repository MichenaudMelvin/Glitch, pull requests merged in 2023-04, with the labels that each got.

#153 Embed appearance FX
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_FireTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_IceTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_PoisonTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_WindTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Crossbow.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Mortar.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_RailGun.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Wizard.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Traps/BP_Trap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Crossbow.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Mortar.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_RailGun.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Wizard.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDrone.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PlacableActor.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PlacableActorData.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Trap.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Turret.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Public/AI/AIPursuitDrone/PursuitDrone.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PlacableActor.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PlacableActorData.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Trap.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Turret.h
Labels: New Feature, Programmation

#151 Embed FMOD + Dissolve textures
  GlitchUE/Config/DefaultGame.ini
  GlitchUE/Content/FMOD/Banks/Master.uasset
  GlitchUE/Content/FMOD/Banks/Musique.uasset
  GlitchUE/Content/FMOD/Buses/Reverb.uasset
  GlitchUE/Content/FMOD/Desktop/Master.bank
  GlitchUE/Content/FMOD/Desktop/Master.strings.bank
  GlitchUE/Content/FMOD/Desktop/Musique.bank
  GlitchUE/Content/FMOD/Events/FMODEVENT_Infiltration.uasset
  GlitchUE/Content/FMOD/Events/Musique/FMODEVENT_Infiltration.uasset
  GlitchUE/Content/FMOD/Events/Musique/M_Infiltration.uasset
  GlitchUE/Content/FMOD/Events/Test.uasset
  GlitchUE/Content/FMOD/PrivateIntegrationData/AssetLookup.uasset
  GlitchUE/Content/FMOD/PrivateIntegrationData/BankLookup.uasset
  GlitchUE/GlitchUE.uproject
Labels: New Feature, Art, Game design

#155 Drones fixes
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDrone.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PlacableActor.h
Labels: Bug fix, Programmation

#156 Focus drones anim
  GlitchUE/Content/Animation/Drones/FocusDrones/ABP_FocusDrones.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/AIFocusCatalyseur/BP_FocusCatalyseurCharacter.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/AIFocusCatalyseur/BT_FocusCatalyseur.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/AIFocusNexus/BP_FocusNexusCharacter.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/AIFocusNexus/BT_FocusNexus.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/BB_FocusAI.uasset
  GlitchUE/Content/Blueprint/AI/Temp/BTService_ChangeMaterial.uasset
  GlitchUE/Content/Blueprint/AI/Temp/M_Aggro.uasset
  GlitchUE/Content/Blueprint/AI/Temp/M_Attack.uasset
  GlitchUE/Source/GlitchUE/Private/AI/GeneralTasks/AttackTarget.cpp
  GlitchUE/Source/GlitchUE/Public/AI/FocusAIController.h
  GlitchUE/Source/GlitchUE/Public/AI/GeneralTasks/AttackTarget.h
Labels: New Feature, Programmation

#159 Clean files
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDrone.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDronePad.cpp
Labels: Bug fix, Update, Art

#162 Slide and coyote time
  GlitchUE/Content/Blueprint/LevelElement/Doors/BP_AbstractDoor.uasset
  GlitchUE/Content/Blueprint/LevelElement/Doors/BP_BasicDoor.uasset
  GlitchUE/Content/Blueprint/Mark/BP_Mark.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Content/Blueprint/Rebords/BP_Edge.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolCharacter.cpp
  GlitchUE/Source/GlitchUE/Private/Mark/Mark.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Inhibiteur.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/ConstructionZone.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Turret.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Public/Mark/Mark.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Inhibiteur.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/ConstructionZone.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
Labels: Bug fix, New Feature, Update, Programmation

#161 FX Catalyseur + Drones
  GlitchUE/Content/VFX/Particles/FX_Enemies/Drones/Pk_ExplodeDrone_Idling.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Drones/Pk_ExplodingDrone_Destruction.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Drones/Pk_SurveillanceDrone_Idling.uasset
  GlitchUE/Content/VFX/Particles/FX_Environment/Pk_Catalyseur.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_AlphabetSpriteSheet.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_Pentagone.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_Pseudos.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_Triangle.uasset
  GlitchUE/Content/VFX/Particles/Textures/White.uasset
Labels: New Feature, Art

#164 Drone_Root
  GlitchUE/Content/Meshs/Drones/Pursuit/AS_Drones_Pursuit_Start.uasset
  GlitchUE/Content/Meshs/Drones/Pursuit/SKEL_Drone_Crystal_Pad.uasset
  GlitchUE/Content/Meshs/Drones/Pursuit/SKEL_Drones_Pursuit.uasset
  GlitchUE/Content/Meshs/Drones/Pursuit/SK_Drones_Pursuit.uasset
Labels: Bug fix

#169 Fix textures shaders tech
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix_Pillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix_SmallPillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Black.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Basic.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Floor.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Celling/SM_TECH_Celling.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Floors/SM_TECH_Floor.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Floors/SM_TECH_N_Floor.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Stairs/SM_Tech_Stairs.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Stairs/SM_Tech_StairsFence.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_2Double_Wall.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_Double_Wall.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_N_Double_Wall.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_N_Wall.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/MPC_Dissolver.uasset
Labels: Bug fix, Update, Art

#173 Plus de Fromage et fix drones
  GlitchUE/Content/Meshs/Drones/Pursuit/PHYS_Drone_Crystal_Pad.uasset
  GlitchUE/Content/Meshs/Drones/Pursuit/PHYS_Drones_Crystal.uasset
  GlitchUE/Content/Meshs/Drones/Pursuit/SK_Drone_Crystal_Pad.uasset
  GlitchUE/Content/Meshs/Drones/Pursuit/SK_Drones_Crystal.uasset
  GlitchUE/Content/Meshs/Drones/Pursuit/SK_Drones_Pursuit.uasset
  GlitchUE/Content/Meshs/Materials/Drones/MI_Drones_Pursuit_BaseMat.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Dissolver_Jet.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Drones_Pursuit_BaseMat.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_MED_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_MED_ORM_.uasset
  GlitchUE/Content/Meshs/Traps/Crystals/PHYS_Crystal.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Dissolver.uasset
Labels: Bug fix, Art

#174 Mesh and materials fix
  GlitchUE/Content/Blueprint/LevelElement/LightElements/BP_LightElement_Chandelier.uasset
  GlitchUE/Content/Blueprint/LevelElement/LightElements/BP_LightElement_Torch.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Door/SM_MED_Stone_DoorFrame.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_4.uasset
Labels: Bug fix, Art
