Repository MichenaudMelvin/Glitch, pull requests merged in 2023-03, with the labels that each got.

#98 PursuitDrone
  GlitchUE/Content/Blueprint/AI/AICamera/BP_CameraPawn.uasset
  GlitchUE/Content/Blueprint/AI/AICamera/Decorators/BTDecorator_CheckCameraBehavior.uasset
  GlitchUE/Content/Blueprint/AI/AICamera/E_CameraBehavior.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BB_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BP_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BT_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/Helpers/FunctionLibrary/BP_UsefullFunctions.uasset
  GlitchUE/Content/Blueprint/Player/UI/WheelAndHotBar/WBP_GameplayModeButton.uasset
  GlitchUE/Content/Blueprint/Player/UI/WheelAndHotBar/WBP_HotBar.uasset
  GlitchUE/Content/Blueprint/Player/UI/WheelAndHotBar/WBP_PlacableObjectButton.uasset
  GlitchUE/Content/Blueprint/Player/UI/WheelAndHotBar/WBP_SelectionButton.uasset
  GlitchUE/Content/Blueprint/Player/UI/WheelAndHotBar/WBP_SubmenuButton.uasset
  GlitchUE/Content/Blueprint/Player/UI/WheelAndHotBar/WBP_Wheel.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AICamera/AICameraPawn.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolController.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDrone.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDroneController.cpp
  GlitchUE/Source/GlitchUE/Private/AI/FocusAIController.cpp
  GlitchUE/Source/GlitchUE/Private/AI/GeneralTasks/MoveToPlayer.cpp
  GlitchUE/Source/GlitchUE/Private/AI/MainAIPawn.cpp
  GlitchUE/Source/GlitchUE/Private/Helpers/FunctionsLibrary/UsefullFunctions.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/PlacableSelection/GameplayModeButton.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/PlacableSelection/HotBar.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/PlacableSelection/PlacableObjectButton.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/PlacableSelection/PlacableSelection.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/PlacableSelection/SelectionButton.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/PlacableSelection/SubMenuButton.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/PlacableSelection/Wheel.cpp
  GlitchUE/Source/GlitchUE/Public/AI/AICamera/AICameraPawn.h
  GlitchUE/Source/GlitchUE/Public/AI/AIPursuitDrone/PursuitDrone.h
  GlitchUE/Source/GlitchUE/Public/AI/AIPursuitDrone/PursuitDroneController.h
  GlitchUE/Source/GlitchUE/Public/AI/GeneralTasks/MoveToPlayer.h
  GlitchUE/Source/GlitchUE/Public/AI/MainAIPawn.h
  GlitchUE/Source/GlitchUE/Public/Helpers/FunctionsLibrary/UsefullFunctions.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PreviewPlacableActor.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/PlacableSelection/GameplayModeButton.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/PlacableSelection/HotBar.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/PlacableSelection/PlacableObjectButton.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/PlacableSelection/PlacableSelection.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/PlacableSelection/SelectionButton.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/PlacableSelection/SubMenuButton.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/PlacableSelection/Wheel.h
Labels: New Feature, Update, Programmation

#101 Slide player
  GlitchUE/Content/Animation/Player/ABP_Player.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
Labels: Update, Game design

#104 Drone pursuit AI
  GlitchUE/Content/Blueprint/AI/AICamera/BT_Camera.uasset
  GlitchUE/Content/Blueprint/AI/AIPatrol/BT_Patrol.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BP_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BT_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/BB_MainBlackboard.uasset
  GlitchUE/Content/Blueprint/AI/GeneralDecorators/BTDecorator_IsPlayerInGlitchZone.uasset
  GlitchUE/Content/Blueprint/GlitchZone/BP_GlitchZone.uasset
  GlitchUE/Content/Blueprint/Nexus/BP_Nexus.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/BP_ConstructionZone.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_FireTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_IceTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_WindTrap.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Source/GlitchUE/Private/AI/GeneralServices/ClearBlackboardKey.cpp
  GlitchUE/Source/GlitchUE/Private/AI/GeneralTasks/AlertNearestAI.cpp
  GlitchUE/Source/GlitchUE/Private/AI/GeneralTasks/MoveToPlayer.cpp
  GlitchUE/Source/GlitchUE/Private/AI/MainAICharacter.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchZones/GlitchZone.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/ConstructionZone.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Trap.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Public/AI/GeneralServices/ClearBlackboardKey.h
  GlitchUE/Source/GlitchUE/Public/AI/GeneralTasks/AlertNearestAI.h
  GlitchUE/Source/GlitchUE/Public/AI/MainAICharacter.h
  GlitchUE/Source/GlitchUE/Public/GlitchZones/GlitchZone.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/ConstructionZone.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Trap.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/TrapData.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
Labels: Update, Programmation

#105 Traps FX
  GlitchUE/Content/Blueprint/FX/BP_StudioCapture.uasset
  GlitchUE/Content/Blueprint/FX/BP_StudioCaptureVertical.uasset
  GlitchUE/Content/Blueprint/FX/BP_TransitionSphereVertical.uasset
  GlitchUE/Content/VFX/Particles/FX_Avatar/Pk_TPDash.uasset
  GlitchUE/Content/VFX/Particles/FX_Towers/FX_Magical/Pk_MagicalShot.uasset
  GlitchUE/Content/VFX/Particles/FX_Towers/FX_Mortar/Pk_MortarExplosion.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_BurningTrap.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_FearSmog.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_FreezeTrap.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_FreezeTrapIdle.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_Slow.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_SlowIdle.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_StunIdle.uasset
  GlitchUE/Content/VFX/Particles/Meshes/SM_Meteor.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_AlphaRemap.uasset
  GlitchUE/Content/VFX/Shaders/RenderTargetDissolve/RT2D_DissolvingTextureVertical.uasset
Labels: New Feature, Art

#106 Fix Dissolver studio capture
  GlitchUE/Content/Meshs/Materials/MF_TextureMatrix.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Dissolver.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver_Emissive.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver_matrix.uasset
Labels: Bug fix, Art

#107 New assets and textures
  GlitchUE/Content/Blueprint/LevelElement/DT_ModumarParts.uasset
  GlitchUE/Content/Blueprint/LevelElement/DT_Pillars.uasset
  GlitchUE/Content/Meshs/Materials/MF_TextureMatrix_Floor.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix_Pillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix_SmallPillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Floor.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Pillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_SmallPillars.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Floors/SM_TECH_Floor_0.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Floors/SM_TECH_N_Floor.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_BasePillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_Pillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_TECH_N_TopPillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/TECH_N_BasePillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/TECH_N_BasePillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/TECH_N_BasePillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/TECH_N_BasePillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/TECH_N_SmallPillar.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver_Floor.uasset
Labels: New Feature, Update, Art

#108 New glitch jauge system
  GlitchUE/Content/Blueprint/AI/AIPatrol/BT_Patrol.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/BP_ConstructionZone.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_IceTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_WindTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Crossbow.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Mortar.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_RailGun.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Crossbow.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Mortar.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_RailGun.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Source/GlitchUE/Private/AI/MainAICharacter.cpp
  GlitchUE/Source/GlitchUE/Private/AI/MainAIPawn.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchInterface.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchUEGameMode.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/ConstructionZone.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PlacableActor.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Trap.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Turret.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Public/AI/MainAICharacter.h
  GlitchUE/Source/GlitchUE/Public/AI/MainAIPawn.h
  GlitchUE/Source/GlitchUE/Public/AI/Waves/Spawner.h
  GlitchUE/Source/GlitchUE/Public/GlitchInterface.h
  GlitchUE/Source/GlitchUE/Public/Mark/Mark.h
  GlitchUE/Source/GlitchUE/Public/Objectives/AbstractObjectif.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/ConstructionZone.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PlacableActor.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Trap.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Turret.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/TurretData.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
Labels: New Feature, Update, Programmation

#109 Embed trap fx
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_FireTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_IceTrap.uasset
Labels: Update, Programmation

#111 New walls + Door assets and textures
  GlitchUE/Content/Blueprint/LevelElement/DT_ModumarParts.uasset
  GlitchUE/Content/Blueprint/LevelElement/DT_Pillars.uasset
  GlitchUE/Content/Blueprint/LevelElement/LightElements/BP_LightElement_Chandelier.uasset
  GlitchUE/Content/Meshs/Materials/MF_New_Inverted_Dissolve.uasset
  GlitchUE/Content/Meshs/Materials/MF_TextureMatrix_Floor.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix_Pillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix_SmallPillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Constent_MED_Mats.uasset
  GlitchUE/Content/Meshs/Materials/M_Flux.uasset
  GlitchUE/Content/Meshs/Materials/M_Flux1.uasset
  GlitchUE/Content/Meshs/Materials/M_Flux2.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Basic.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Floor.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Pillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_SmallPillars.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_MED_N_TopPillars_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_MED_N_TopPillars_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_MED_N_TopPillars_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Pilllars/SM_MED_N_TopPillars_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_DoorFrame.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_Half_DoubleWall.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_N_Double_Wall.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_N_Half_Wall.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_N_Wall.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_UpDoor.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver_Floor.uasset
Labels: New Feature, Update, Art

#112 Fix popcorn and drones crash + fix nexus and catalyseur behavior
  GlitchUE/Config/DefaultEngine.ini
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BT_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/BP_MainAICharacter.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/AIFocusNexus/BT_FocusNexus.uasset
  GlitchUE/Content/Blueprint/AI/GeneralDecorators/BTDecorator_IsPlayerInSight.uasset
  GlitchUE/Content/Blueprint/FX/BP_StudioCapture.uasset
  GlitchUE/Content/Blueprint/FX/BP_StudioCaptureVertical.uasset
  GlitchUE/Content/Blueprint/FX/BP_TransitionSphere.uasset
  GlitchUE/Content/Blueprint/FX/BP_TransitionSphereVertical.uasset
  GlitchUE/Content/Blueprint/GlitchZone/BP_GlitchZone.uasset
  GlitchUE/Content/Blueprint/Helpers/Editor/EUW_GetDistanceFromClass.uasset
  GlitchUE/Content/Blueprint/Helpers/Editor/EUW_SpawnDependencies.uasset
  GlitchUE/Content/Blueprint/Menu/MainMenu/WBP_MainTitle.uasset
  GlitchUE/Content/Blueprint/Nexus/BP_Catalyseur.uasset
  GlitchUE/Content/Blueprint/Nexus/BP_Nexus.uasset
  GlitchUE/Content/Blueprint/Objectives/BP_Inhibiteur.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Content/Blueprint/Player/Controllers/BP_PC_MainPlayerController.uasset
  GlitchUE/Content/VFX/Particles/FX_Towers/FX_Magical/Pk_MagicalShot.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_BurningTrap.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AIFocusCatalyseur/Services/SetNearestCatalyseur.cpp
  GlitchUE/Source/GlitchUE/Private/AI/FocusAIController.cpp
  GlitchUE/Source/GlitchUE/Private/AI/GeneralTasks/AlertNearestAI.cpp
  GlitchUE/Source/GlitchUE/Private/AI/GeneralTasks/SelfDestroy.cpp
  GlitchUE/Source/GlitchUE/Private/Helpers/FunctionsLibrary/UsefullFunctions.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/AbstractObjectif.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Catalyseur.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PreviewPlacableActor.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Public/AI/MainAIController.h
  GlitchUE/Source/GlitchUE/Public/Objectives/AbstractObjectif.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/ConstructionZone.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PreviewPlacableActor.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Trap.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
Labels: Bug fix, Update, Programmation

#114 Debug commands
  GlitchUE/Source/GlitchUE/Private/GlitchUEGameMode.cpp
  GlitchUE/Source/GlitchUE/Public/GlitchUEGameMode.h
Labels: New Feature, Programmation

#117 Up mesh door
  GlitchUE/Content/Blueprint/LevelElement/DT_ModumarParts.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_MED_Wall_UpDoor.uasset
Labels: New Feature, Update, Art

#116 Player Character mesh
  GlitchUE/Content/Animation/Player/ABP_Player.uasset
  GlitchUE/Content/Animation/Player/AS_Crouch.uasset
  GlitchUE/Content/Animation/Player/AS_CrouchIdle.uasset
  GlitchUE/Content/Animation/Player/AS_Idle.uasset
  GlitchUE/Content/Animation/Player/AS_Jog.uasset
  GlitchUE/Content/Animation/Player/AS_JumpEnd.uasset
  GlitchUE/Content/Animation/Player/AS_JumpLoop.uasset
  GlitchUE/Content/Animation/Player/AS_JumpStart.uasset
  GlitchUE/Content/Animation/Player/AS_Run.uasset
  GlitchUE/Content/Animation/Player/AS_Slide.uasset
  GlitchUE/Content/Animation/Player/BS_GroundMovements.uasset
  GlitchUE/Content/Animation/Player/PHYS_Player.uasset
  GlitchUE/Content/Animation/Player/SKEL_Player.uasset
  GlitchUE/Content/Animation/Player/SK_Player.uasset
  GlitchUE/Content/Meshs/Materials/Player/M_Arms.uasset
  GlitchUE/Content/Meshs/Materials/Player/M_Cap.uasset
  GlitchUE/Content/Meshs/Materials/Player/M_Pants.uasset
  GlitchUE/Content/Meshs/Materials/Player/M_Scarf.uasset
  GlitchUE/Content/Meshs/Materials/Player/M_Tabard.uasset
  GlitchUE/Content/Meshs/Materials/Player/M_Tunic.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Arms_D.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Arms_M.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Arms_R.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Cap_D.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Cap_M.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Cap_R.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Pants_D.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Pants_R.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Scarf_D.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Scarf_M.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Scarf_R.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Tabard_D.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Tabard_M.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Tabard_R.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Tunic_D.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Tunic_M.uasset
  GlitchUE/Content/Meshs/Materials/Player/T_Tunic_R.uasset
Labels: New Feature, Art

#122 Fix FX
  GlitchUE/Content/VFX/Particles/FX_Towers/FX_Crossbow/Pk_ArrowShotStraight.uasset
  GlitchUE/Content/VFX/Particles/FX_Towers/FX_Mortar/Pk_MortarExplosion.uasset
  GlitchUE/Content/VFX/Particles/FX_Towers/FX_Mortar/Pk_MortarShot.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_FearSmog.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_Slow.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_SlowIdle.uasset
  GlitchUE/Content/VFX/Shaders/GlitchedMesh/FXS_GlitchingFX.uasset
  GlitchUE/Content/VFX/Shaders/GlitchedMesh/M_GlitchBlue.uasset
  GlitchUE/Content/VFX/Shaders/GlitchedMesh/M_GlitchGreen.uasset
  GlitchUE/Content/VFX/Shaders/GlitchedMesh/M_GlitchRed.uasset
  GlitchUE/Content/VFX/Shaders/GlitchedMesh/M_GlitchingFX.uasset
  GlitchUE/Content/VFX/Shaders/GlitchedMesh/M_GlitchingMat.uasset
  GlitchUE/Content/VFX/Shaders/GlitchedMesh/M_WireGlitch.uasset
  GlitchUE/Content/VFX/Shaders/GlitchedMesh/N_GlitchingFX.uasset
Labels: Bug fix, Update, Art

#123 Replace the static mesh trap with skeletal mesh
  GlitchUE/Content/Blueprint/Helpers/Editor/EUW_SpawnDependencies.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_FireTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_IceTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_PoisonTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_WindTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_Crossbow.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_RailGun.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Traps/BP_Trap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Crossbow.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Mortar.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_RailGun.uasset
  GlitchUE/Content/Maps/TestingMap.umap
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PlacableActor.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PreviewPlacableActor.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Trap.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Turret.cpp
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PlacableActor.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PlacableActorData.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PreviewPlacableActor.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Trap.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/TrapData.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Turret.h
Labels: Update, Programmation

#130 Warn logs fix
  GlitchUE/Content/Animation/Player/ABP_Player.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/AIFocusCatalyseur/BB_FocusCatalyseur.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/BB_FocusAI.uasset
  GlitchUE/Content/Blueprint/LevelElement/LightElements/BP_LightElement.uasset
  GlitchUE/Content/Blueprint/Objectives/BP_Catalyseur.uasset
  GlitchUE/Content/Blueprint/Objectives/UI/WBP_WaveManaging.uasset
  GlitchUE/Content/Maps/TestingMap.umap
Labels: Bug fix, Programmation

#131 Improve glitch zone
  GlitchUE/Content/Blueprint/GlitchZone/BP_GlitchZone.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/MPC_GlitchZone.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/M_GlitchCharacter.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/M_GlitchCharacter_Arms.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/M_GlitchCharacter_Pants.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/M_GlitchZone.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/PPM_Glitch_UI.uasset
  GlitchUE/Source/GlitchUE/Private/GlitchUEGameMode.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchZones/GlitchZone.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Public/GlitchUEGameMode.h
  GlitchUE/Source/GlitchUE/Public/GlitchZones/GlitchZone.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
  GlitchUE/Source/GlitchUE/Public/Saves/AbstractSave.h
  GlitchUE/Source/GlitchUE/Public/Saves/WorldSave.h
Labels: Update, Programmation

#135 Tchat
  GlitchUE/Config/DefaultInput.ini
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Traps/DA_IceTrap.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Data/Turrets/DA_RailGun.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Crossbow.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Mortar.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_RailGun.uasset
  GlitchUE/Content/Blueprint/PlacableObjects/Turrets/BP_Wizard.uasset
  GlitchUE/Content/Blueprint/Player/Controllers/BP_PC_MainPlayerController.uasset
  GlitchUE/Content/Blueprint/Player/UI/Tchat/WBP_Tchat.uasset
  GlitchUE/Content/Blueprint/Player/UI/Tchat/WBP_TchatLine.uasset
  GlitchUE/Content/Maps/TestingMap.umap
  GlitchUE/Content/UI/Fonts/FF_Tchat.uasset
  GlitchUE/Content/UI/Fonts/FONT_Tchat.uasset
  GlitchUE/GlitchUE.uproject
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Trap.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Turret.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/Tchat/Tchat.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/Tchat/TchatLine.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/Tchat/TchatLineData.cpp
  GlitchUE/Source/GlitchUE/Public/Player/UI/Tchat/Tchat.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/Tchat/TchatLine.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/Tchat/TchatLineData.h
Labels: Update, Programmation

#136 Turret Meshs
  GlitchUE/Content/Maps/Mesh_Testing.umap
  GlitchUE/Content/Meshs/Materials/Objectives/M_Inhibiteur_Emissive.uasset
  GlitchUE/Content/Meshs/Traps/FireTrap/PHYS_FireTrap.uasset
  GlitchUE/Content/Meshs/Traps/IceTrap/PHYS_IceTrap.uasset
  GlitchUE/Content/Meshs/Traps/PoisonTrap/PHYS_PoisonTrap.uasset
  GlitchUE/Content/Meshs/Traps/WindTrap/PHYS_WindTrap.uasset
  GlitchUE/Content/Meshs/Turrets/CrossBow/PHYS_CrossBow_Head.uasset
  GlitchUE/Content/Meshs/Turrets/CrossBow/SM_CrossBow_Base.uasset
  GlitchUE/Content/Meshs/Turrets/CrossBow/SM_CrossBow_Pillar.uasset
  GlitchUE/Content/Meshs/Turrets/Mortar/AS_Mortar_Head.uasset
  GlitchUE/Content/Meshs/Turrets/Mortar/PHYS_Mortar_Head.uasset
  GlitchUE/Content/Meshs/Turrets/Mortar/SK_Mortar_Head.uasset
  GlitchUE/Content/Meshs/Turrets/Mortar/SM_Mortar_Base.uasset
  GlitchUE/Content/Meshs/Turrets/Mortar/SM_Mortar_Pillar.uasset
  GlitchUE/Content/Meshs/Turrets/Railgun/SK_Railgun_Head.uasset
  GlitchUE/Content/Meshs/Turrets/Railgun/SM_Railgun_Base.uasset
  GlitchUE/Content/Meshs/Turrets/Railgun/SM_Railgun_Pillar.uasset
  GlitchUE/Content/Meshs/Turrets/Wizard/AS_Wizard.uasset
  GlitchUE/Content/Meshs/Turrets/Wizard/PHYS_Wizard.uasset
  GlitchUE/Content/Meshs/Turrets/Wizard/SK_Wizard.uasset
  GlitchUE/Content/Meshs/Turrets/Wizard/SM_Wizard_Base.uasset
Labels: Bug fix, Art

#139 Drones
  GlitchUE/Content/Maps/Mesh_Testing.umap
  GlitchUE/Content/Meshs/Drones/AS_Drones_Pursuit_Destrustruction.uasset
  GlitchUE/Content/Meshs/Drones/AS_Drones_Pursuit_Pad.uasset
  GlitchUE/Content/Meshs/Drones/AS_Drones_Pursuit_Start.uasset
  GlitchUE/Content/Meshs/Drones/PHYS_Drones_Guard.uasset
  GlitchUE/Content/Meshs/Drones/PHYS_Drones_Pursuit.uasset
  GlitchUE/Content/Meshs/Drones/PHYS_Drones_Pursuit_Pad.uasset
  GlitchUE/Content/Meshs/Drones/SKEL_Drones_Guard.uasset
  GlitchUE/Content/Meshs/Drones/SKEL_Drones_Pursuit.uasset
  GlitchUE/Content/Meshs/Drones/SKEL_Drones_Pursuit_Pad.uasset
  GlitchUE/Content/Meshs/Drones/SK_Drones_Guard.uasset
  GlitchUE/Content/Meshs/Drones/SK_Drones_Pursuit.uasset
  GlitchUE/Content/Meshs/Drones/SK_Drones_Pursuit_Pad.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Drones_Pursuit_BaseMat.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Drones_Pursuit_Emissive.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Drones_Pursuit_Jet.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Drone_Pursuit_M.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Drone_Pursuit_M2.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Drones_Pursuit_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Drones_Pursuit_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Drones_Pursuit_ORM.uasset
Labels: Update, Art

#145 Pursuit drones now uses pads
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BB_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BP_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BP_PursuitDronePad.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BT_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/BB_MainBlackboard.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDrone.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDroneController.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDronePad.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/Tasks/LaunchPursuitDrone.cpp
  GlitchUE/Source/GlitchUE/Private/AI/GeneralTasks/SetPawnTransform.cpp
  GlitchUE/Source/GlitchUE/Private/AI/MainAIController.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchZones/GlitchZone.cpp
  GlitchUE/Source/GlitchUE/Public/AI/AIPursuitDrone/PursuitDrone.h
  GlitchUE/Source/GlitchUE/Public/AI/AIPursuitDrone/PursuitDroneController.h
  GlitchUE/Source/GlitchUE/Public/AI/AIPursuitDrone/PursuitDronePad.h
  GlitchUE/Source/GlitchUE/Public/AI/AIPursuitDrone/Tasks/LaunchPursuitDrone.h
  GlitchUE/Source/GlitchUE/Public/AI/GeneralTasks/SetPawnTransform.h
  GlitchUE/Source/GlitchUE/Public/GlitchZones/GlitchZone.h
  GlitchUE/Source/GlitchUE/Public/Saves/WorldSave.h
Labels: Update, Programmation

#144 Pursuit and Seeker
  GlitchUE/Content/Meshs/Drones/PHYS_Drones_Pursuit.uasset
  GlitchUE/Content/Meshs/Drones/PHYS_Drones_Pursuit_Pad.uasset
  GlitchUE/Content/Meshs/Drones/SK_Drones_Pursuit_Pad.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/AS_Seeker_Alert.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/AS_Seeker_Detection_Anim.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/AS_Seeker_Idle.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/AS_Seeker_Start_Alert.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/PHYS_Seeker.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/SKEL_Seeker.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/SK_Seeker.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Drone_Seeker.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Drones_Emissive.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Drones_Pursuit_Emissive.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Drones_Pursuit_Pad_BaseMat.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Drones_Pursuit_Pad_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Drones_Pursuit_Pad_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Drones_Pursuit_Pad_ORM.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Seeker_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Seeker_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Drones/T_Seeker_ORM.uasset
Labels: Bug fix, Update, Art

#146 New Dissolve
  GlitchUE/Content/Blueprint/FX/BP_Dissolver.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/M_GlitchZone.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/T_Glitch_B.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/T_Glitch_G.uasset
  GlitchUE/Content/Meshs/Materials/Glitch/T_Glitch_R.uasset
  GlitchUE/Content/Meshs/Materials/MF_New_Inverted_Dissolve.uasset
  GlitchUE/Content/Meshs/Materials/MF_TextureMatrix.uasset
  GlitchUE/Content/Meshs/Materials/MF_TextureMatrix_Floor.uasset
  GlitchUE/Content/Meshs/Materials/MI_Disolver_MED_Mats.uasset
  GlitchUE/Content/Meshs/Materials/MI_Disolver_MED_Metals.uasset
  GlitchUE/Content/Meshs/Materials/MI_Disolver_TECH_Emissive.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix_Pillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Black_Matrix_SmallPillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Buisson.uasset
  GlitchUE/Content/Meshs/Materials/M_Constent_MED_Glass.uasset
  GlitchUE/Content/Meshs/Materials/M_Constent_MED_Mats.uasset
  GlitchUE/Content/Meshs/Materials/M_Constent_MED_Metals.uasset
  GlitchUE/Content/Meshs/Materials/M_Constent_TECH_Emissive.uasset
  GlitchUE/Content/Meshs/Materials/M_Constent_TECH_Glass.uasset
  GlitchUE/Content/Meshs/Materials/M_Constent_TECH_Mats.uasset
  GlitchUE/Content/Meshs/Materials/M_Constent_TECH_Metals.uasset
  GlitchUE/Content/Meshs/Materials/M_Flux.uasset
  GlitchUE/Content/Meshs/Materials/M_Flux1.uasset
  GlitchUE/Content/Meshs/Materials/M_Flux2.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Basic.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Floor.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_Pillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Hexago_Mat_SmallPillars.uasset
  GlitchUE/Content/Meshs/Materials/M_Mortar_Glow.uasset
  GlitchUE/Content/Meshs/Materials/M_RailGun_Glow.uasset
  GlitchUE/Content/Meshs/Materials/M_TestMatrix.uasset
  GlitchUE/Content/Meshs/Materials/Props/M_Props_Glass.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_Glitch_RGB.uasset
  GlitchUE/Content/Meshs/Props/Weapon/Lance/SM_MED_Lance_01.uasset
  GlitchUE/Content/Meshs/Props/Weapon/Lance/SM_MED_Lance_02.uasset
  GlitchUE/Content/Meshs/Props/Weapon/Lance/SM_MED_Lance_03.uasset
  GlitchUE/Content/Meshs/Props/Weapon/Lance/SM_MED_Lance_04.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/MF_Dissolver.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/MF_Inverted_Dissolver.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/MPC_Dissolver.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Dissolver.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver_Emissive.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver_Floor.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver_matrix.uasset
Labels: Update, Art

#147 Drones Enemy
  GlitchUE/Content/Meshs/Drones/Enemies/AS_Enemy_Fire_Anim.uasset
  GlitchUE/Content/Meshs/Drones/Enemies/AS_Enemy_Idle.uasset
  GlitchUE/Content/Meshs/Drones/Enemies/AS_Enemy_Reload_Anim.uasset
  GlitchUE/Content/Meshs/Drones/Enemies/PHYS_Enemy_Heavy.uasset
  GlitchUE/Content/Meshs/Drones/Enemies/PHYS_Enemy_Light.uasset
  GlitchUE/Content/Meshs/Drones/Enemies/PHYS_Enemy_Normal.uasset
  GlitchUE/Content/Meshs/Drones/Enemies/SKEL_Enemy.uasset
  GlitchUE/Content/Meshs/Drones/Enemies/SK_Enemy_Heavy.uasset
  GlitchUE/Content/Meshs/Drones/Enemies/SK_Enemy_Light.uasset
  GlitchUE/Content/Meshs/Drones/Enemies/SK_Enemy_Normal.uasset
  GlitchUE/Content/Meshs/Materials/Drones/M_Drone_Glass.uasset
Labels: Update, Art

#148 Construction materials
  GlitchUE/Content/VFX/Particles/FX_Environment/Pk_GreenSmoke.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/MF_AppearanceFunct.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr_Crossbow.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr_FireTrap.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr_IceTrap.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr_Magical.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr_Mortar.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr_PoisonTrap.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr_Railgun.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr_WindTrap.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_AppearanceConstr_Wizard.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_Wireframe.uasset
  GlitchUE/Content/VFX/Shaders/TowerConstruction/M_Wireframe_Inst.uasset
Labels: New Feature, Art

#150 Embed Seeker animations
  .gitignore
  GlitchUE/Build/Windows/Application.ico
  GlitchUE/Config/DefaultEngine.ini
  GlitchUE/Content/Animation/Drones/Seeker/ABP_Seeker.uasset
  GlitchUE/Content/Blueprint/AI/AIPatrol/BP_PatrolCharacter.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Content/Blueprint/Rebords/BP_Edge.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/AS_Seeker_Alert.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/AS_Seeker_Detection_Anim.uasset
  GlitchUE/Content/Meshs/Drones/Seeker/AS_Seeker_Start_Alert.uasset
  GlitchUE/Content/Splash/EdSplash.png
  GlitchUE/Content/Splash/EdSplash.uasset
  GlitchUE/GlitchUE.png
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolCharacter.cpp
  GlitchUE/Source/GlitchUE/Private/AI/MainAICharacter.cpp
  GlitchUE/Source/GlitchUE/Private/Components/SightComponent.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Public/Components/SightComponent.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
  Others/GlitchUE.ico
  Others/Logo.png
Labels: Bug fix, New Feature, Update, Programmation
