Repository MichenaudMelvin/Glitch, pull requests merged in 2023-05, with the labels that each got.

#190 New Game design featues
  GlitchUE/Content/Animation/Drones/FocusDrones/ABP_FocusDrones.uasset
  GlitchUE/Content/Animation/Drones/Seeker/ABP_Seeker.uasset
  GlitchUE/Content/Animation/Player/ABP_Player.uasset
  GlitchUE/Content/Blueprint/AI/AISpawner/BP_WaveManager.uasset
  GlitchUE/Content/Blueprint/Player/BP_MainPlayer.uasset
  GlitchUE/Content/Blueprint/Player/Controllers/BP_PC_MainPlayerController.uasset
  GlitchUE/Content/Blueprint/Player/UI/WBP_DisplayStats.uasset
  GlitchUE/Content/Blueprint/Player/UI/WBP_DisplayWaveTimer.uasset
  GlitchUE/Content/Blueprint/UI/WBP_TimerWidget.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AIFocusCatalyseur/Services/SetNearestCatalyseur.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolCharacter.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDrone.cpp
  GlitchUE/Source/GlitchUE/Private/AI/Waves/WaveManager.cpp
  GlitchUE/Source/GlitchUE/Private/Components/ActivableComponent.cpp
  GlitchUE/Source/GlitchUE/Private/FX/Dissolver.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchUEGameMode.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchZones/GlitchZone.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/AbstractObjectif.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Catalyseur.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Inhibiteur.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Nexus.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PlacableActor.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayerController.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/TimerWidget.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Player/PlayerStats.cpp
  GlitchUE/Source/GlitchUE/Public/AI/Waves/Spawner.h
  GlitchUE/Source/GlitchUE/Public/AI/Waves/WaveManager.h
  GlitchUE/Source/GlitchUE/Public/FX/Dissolver.h
  GlitchUE/Source/GlitchUE/Public/GlitchUEGameMode.h
  GlitchUE/Source/GlitchUE/Public/GlitchZones/GlitchZone.h
  GlitchUE/Source/GlitchUE/Public/Objectives/AbstractObjectif.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Catalyseur.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Inhibiteur.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Nexus.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayerController.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/TimerWidget.h
  GlitchUE/Source/GlitchUE/Public/Saves/StealthSave.h
  GlitchUE/Source/GlitchUE/Public/Saves/TowerDefenseSave.h
  GlitchUE/Source/GlitchUE/Public/Saves/WorldSave.h
  GlitchUE/Source/GlitchUE/Public/UI/Player/PlayerStats.h
Labels: Bug fix, New Feature, Update, Programmation

#193 CatalyzeurZones and Compass components
  GlitchUE/Config/DefaultEngine.ini
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BP_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/AIFocusCatalyseur/BP_FocusCatalyseurCharacter.uasset
  GlitchUE/Content/Blueprint/AI/FocusAI/AIFocusNexus/BP_FocusNexusCharacter.uasset
  GlitchUE/Content/Blueprint/GlitchZone/BP_CatalyseurZone.uasset
  GlitchUE/Content/Blueprint/GlitchZone/BP_GlitchZone.uasset
  GlitchUE/Content/Blueprint/Helpers/Editor/EUW_EditorNavigation.uasset
  GlitchUE/Content/Blueprint/LevelElement/Doors/BP_AbstractDoor.uasset
  GlitchUE/Content/Blueprint/LevelElement/Doors/BP_BasicDoor.uasset
  GlitchUE/Content/VFX/Particles/FX_Enemies/Pk_FearedStatus.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_SpritesheetFear.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolCharacter.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/PursuitDrone.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPursuitDrone/Tasks/LaunchPursuitDrone.cpp
  GlitchUE/Source/GlitchUE/Private/AI/MainAIController.cpp
  GlitchUE/Source/GlitchUE/Private/Components/CompassComponent.cpp
  GlitchUE/Source/GlitchUE/Private/Components/CompassIcon.cpp
  GlitchUE/Source/GlitchUE/Private/Components/CompassPivotIcon.cpp
  GlitchUE/Source/GlitchUE/Private/Components/HealthComponent.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchUEGameMode.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchZones/CatalyseurZone.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchZones/GlitchZone.cpp
  GlitchUE/Source/GlitchUE/Private/LevelElements/AbstractDoor.cpp
  GlitchUE/Source/GlitchUE/Private/LevelElements/BasicDoor.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Catalyseur.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Inhibiteur.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/ConstructionZone.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PlacableActor.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Trap.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Turret.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayerController.cpp
  GlitchUE/Source/GlitchUE/Public/AI/AIPatrol/PatrolCharacter.h
  GlitchUE/Source/GlitchUE/Public/AI/AIPursuitDrone/PursuitDrone.h
  GlitchUE/Source/GlitchUE/Public/Components/CompassComponent.h
  GlitchUE/Source/GlitchUE/Public/Components/CompassIcon.h
  GlitchUE/Source/GlitchUE/Public/Components/CompassPivotIcon.h
  GlitchUE/Source/GlitchUE/Public/Components/HealthComponent.h
  GlitchUE/Source/GlitchUE/Public/GlitchUEGameMode.h
  GlitchUE/Source/GlitchUE/Public/GlitchZones/CatalyseurZone.h
  GlitchUE/Source/GlitchUE/Public/LevelElements/AbstractDoor.h
  GlitchUE/Source/GlitchUE/Public/LevelElements/BasicDoor.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Catalyseur.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Inhibiteur.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PlacableActor.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Trap.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Turret.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
  GlitchUE/Source/GlitchUE/Public/Saves/WorldSave.h
Labels: Bug fix, New Feature, Update, Programmation

#192 Diffuse texture
  GlitchUE/Content/Meshs/Compass/SM_Arrow.uasset
  GlitchUE/Content/Meshs/Compass/SM_EnemyPointer.uasset
  GlitchUE/Content/Meshs/Compass/SM_Locker.uasset
  GlitchUE/Content/Meshs/Materials/Compass/M_Arrow.uasset
  GlitchUE/Content/Meshs/Materials/Compass/M_EnemyPointer.uasset
  GlitchUE/Content/Meshs/Materials/Compass/M_Locker.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Compass/T_EnemyPointer_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Compass/T_EnemyPointer_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Compass/T_EnemyPointer_ORM.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Compass/T_Locker_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Compass/T_Locker_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/Compass/T_Locker_ORM.uasset
  GlitchUE/Content/UI/Fonts/FF_MenuFont.uasset
  GlitchUE/Content/UI/Fonts/FONT_MenuFont.uasset
  GlitchUE/Content/UI/Menu/T_ButtonHovering.uasset
  GlitchUE/Content/UI/Menu/T_ButtonMainMenuNonHovered.uasset
  GlitchUE/Content/UI/Player/T_LifeHalf.uasset
  GlitchUE/Content/UI/Player/T_LifeHeart.uasset
  GlitchUE/Content/UI/Settings/T_BlocSettings.uasset
  GlitchUE/Content/UI/Settings/T_BoolFalse.uasset
  GlitchUE/Content/UI/Settings/T_BoolTrue.uasset
  GlitchUE/Content/UI/Settings/T_BoolTrueHover.uasset
  GlitchUE/Content/UI/Settings/T_ContainerList.uasset
  GlitchUE/Content/UI/Settings/T_DownArrow.uasset
  GlitchUE/Content/UI/Settings/T_Slider.uasset
  GlitchUE/Content/UI/Settings/T_SliderBase.uasset
  GlitchUE/Content/VFX/Particles/FX_Traps/Pk_FearSmog.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_Diffuse.uasset
  GlitchUE/Source/GlitchUE/Private/Player/UI/Stats/Heart.cpp
  GlitchUE/Source/GlitchUE/Public/Player/UI/Stats/Heart.h
Labels: Bug fix, Art

#196 Multiples fix on saves and settings
  GlitchUE/Content/Blueprint/AI/AISpawner/BP_Spawner.uasset
  GlitchUE/Content/Blueprint/Player/UI/WBP_VideoSettings.uasset
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolCharacter.cpp
  GlitchUE/Source/GlitchUE/Private/AI/GeneralDecorators/IsPlayerInGlitchZone.cpp
  GlitchUE/Source/GlitchUE/Private/AI/MainAIController.cpp
  GlitchUE/Source/GlitchUE/Private/AI/Waves/WaveManager.cpp
  GlitchUE/Source/GlitchUE/Private/FX/Dissolver.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchUEGameMode.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Catalyseur.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Inhibiteur.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PlacableActor.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Trap.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/Turret.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/Settings/VideoSettingsMenu.cpp
  GlitchUE/Source/GlitchUE/Public/AI/AIPatrol/PatrolCharacter.h
  GlitchUE/Source/GlitchUE/Public/FX/Dissolver.h
  GlitchUE/Source/GlitchUE/Public/GlitchUEGameMode.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Catalyseur.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Inhibiteur.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/ConstructionZone.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/PlacableActor.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Trap.h
  GlitchUE/Source/GlitchUE/Public/PlacableObject/Turret.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/Settings/VideoSettingsMenu.h
  GlitchUE/Source/GlitchUE/Public/Saves/Settings/VideoSettingsSave.h
  GlitchUE/Source/GlitchUE/Public/Saves/TowerDefenseSave.h
Labels: Bug fix, Programmation

#197 New AI sound system
  GlitchUE/Config/DefaultEngine.ini
  GlitchUE/Content/Animation/Drones/Seeker/ABP_Seeker.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BP_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/GlitchZone/BP_CatalyseurZone.uasset
  GlitchUE/Content/Blueprint/GlitchZone/BP_GlitchZone.uasset
  GlitchUE/Content/Blueprint/LevelElement/Doors/BP_BasicDoor.uasset
  GlitchUE/Content/Blueprint/Menu/MainMenu/WBP_MainTitle.uasset
  GlitchUE/Content/Blueprint/Objectives/BP_Catalyseur.uasset
  GlitchUE/Content/Blueprint/Player/Controllers/BP_PC_MenuController.uasset
  GlitchUE/Content/Blueprint/Player/UI/Stats/WBP_Heart.uasset
  GlitchUE/GlitchUE.uproject
  GlitchUE/Source/GlitchUE/GlitchUE.Build.cs
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolCharacter.cpp
  GlitchUE/Source/GlitchUE/Private/AI/AIPatrol/PatrolController.cpp
  GlitchUE/Source/GlitchUE/Private/Components/CompassIcon.cpp
  GlitchUE/Source/GlitchUE/Private/Components/CompassPivotIcon.cpp
  GlitchUE/Source/GlitchUE/Private/Components/HearingComponent.cpp
  GlitchUE/Source/GlitchUE/Private/Components/HearingTriggerComponent.cpp
  GlitchUE/Source/GlitchUE/Private/LevelElements/AbstractDoor.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Catalyseur.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Inhibiteur.cpp
  GlitchUE/Source/GlitchUE/Private/Physic/CustomPhysicalMat.cpp
  GlitchUE/Source/GlitchUE/Private/PlacableObject/PlacableActor.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Public/AI/AIPatrol/PatrolCharacter.h
  GlitchUE/Source/GlitchUE/Public/AI/AIPatrol/PatrolController.h
  GlitchUE/Source/GlitchUE/Public/Components/CompassIcon.h
  GlitchUE/Source/GlitchUE/Public/Components/HealthComponent.h
  GlitchUE/Source/GlitchUE/Public/Components/HearingComponent.h
  GlitchUE/Source/GlitchUE/Public/Components/HearingTriggerComponent.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Catalyseur.h
  GlitchUE/Source/GlitchUE/Public/Physic/CustomPhysicalMat.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
Labels: Bug fix, New Feature, Update, Programmation

#199 Packages fix
  GlitchUE/Config/DefaultGame.ini
  GlitchUE/Content/Blueprint/Player/UI/WBP_GameplaySettings.uasset
  GlitchUE/Content/Maps/Level_Tristan.umap
  GlitchUE/Source/GlitchUE/Private/Components/HearingComponent.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Catalyseur.cpp
  GlitchUE/Source/GlitchUE/Private/Objectives/Inhibiteur.cpp
  GlitchUE/Source/GlitchUE/Private/Player/MainPlayer.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/Settings/GameplaySettingsMenu.cpp
  GlitchUE/Source/GlitchUE/Public/Objectives/Catalyseur.h
  GlitchUE/Source/GlitchUE/Public/Objectives/Inhibiteur.h
  GlitchUE/Source/GlitchUE/Public/Player/MainPlayer.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/Settings/GameplaySettingsMenu.h
  GlitchUE/Source/GlitchUE/Public/Saves/Settings/GameplaySettingsSave.h
Labels: Bug fix, Programmation

#195 Update new material TECH + Add new Tower Defense music
  GlitchUE/Content/FMOD/Desktop/Master.bank
  GlitchUE/Content/FMOD/PrivateIntegrationData/AssetLookup.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Floors/MI_TECH_Black_Floor.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Floors/MI_TECH_Flux_Floor.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Floors/M_TECH_Ceiling.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Floors/M_TECH_Mat_Floor.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/M_TECH_Black.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/M_TECH_Flux.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Pillars/M_Black_Matrix_SmallPillars.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Walls/MI_TECH_Flux_1-1.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Walls/MI_TECH_Flux_1-2.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Walls/MI_TECH_Flux_2-1.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Walls/MI_TECH_Flux_2-2.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Walls/M_TECH_Flux.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Floors/T_Floor_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Floors/T_Floor_M.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Floors/T_Floor_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Floors/T_Planche_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Floors/T_Planche_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Floors/T_Planche_R.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_Black-Wall_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_Mask_TchWall.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_Mask_TchWall_R.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_1-1_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_1-1_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_1-1_R.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_1-2_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_1-2_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_1-2_R.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_2-1_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_2-1_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_2-1_R.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_2-2_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_2-2_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_Wall_2-2_R.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_brick_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_brick_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/ModularKit/Walls/T_TECH_brick_R.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_Black-Wall_Texture_png_normal_3.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_Floor_D.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_Floor_M.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_Floor_N.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_Mask_TchWall.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_Mask_TchWall_R.uasset
  GlitchUE/Content/Meshs/Materials/Textures/T_brick_normal.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Celling/SM_TECH_Celling.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Ornement/SM_TECH_Fence.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Walls/SM_TECH_N_Wall.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver.uasset
  GlitchUE/Content/VFX/Shaders/Dissolver/M_Inverted_Dissolver_matrix.uasset
  GlitchUE/Source/GlitchUE/Private/AI/Waves/WaveManager.cpp
  GlitchUE/Source/GlitchUE/Private/Audio/AudioManager.cpp
  GlitchUE/Source/GlitchUE/Public/AI/Waves/WaveManager.h
  GlitchUE/Source/GlitchUE/Public/Audio/AudioManager.h
Labels: New Feature, Update, Art, Audio

#208 Multiple popup node + stealth timer can be disabled in tutorial gamemode
  GlitchUE/Content/Blueprint/Player/Gamemodes/BP_TutorialGamemode.uasset
  GlitchUE/Source/GlitchUE/Private/Gamemodes/TutorialGameMode.cpp
  GlitchUE/Source/GlitchUE/Private/UI/Player/PopUpWidget.cpp
  GlitchUE/Source/GlitchUE/Public/Gamemodes/TutorialGameMode.h
  GlitchUE/Source/GlitchUE/Public/GlitchUEGameMode.h
  GlitchUE/Source/GlitchUE/Public/LevelElements/AbstractDoor.h
  GlitchUE/Source/GlitchUE/Public/UI/Player/PopUpWidget.h
Labels: New Feature, Programmation

#210 Tchat crash + hearing comp crash + ai now open doors
  GlitchUE/Content/Blueprint/AI/AIPatrol/BT_Patrol.uasset
  GlitchUE/Content/Blueprint/AI/AIPursuitDrone/BT_PursuitDrone.uasset
  GlitchUE/Content/Blueprint/UI/Player/WBP_PopUp.uasset
  GlitchUE/Source/GlitchUE/Private/Components/HearingComponent.cpp
  GlitchUE/Source/GlitchUE/Private/Components/HearingTriggerComponent.cpp
  GlitchUE/Source/GlitchUE/Private/GlitchZones/CatalyseurZone.cpp
  GlitchUE/Source/GlitchUE/Private/LevelElements/AbstractDoor.cpp
  GlitchUE/Source/GlitchUE/Private/Player/UI/Tchat/Tchat.cpp
  GlitchUE/Source/GlitchUE/Public/Components/HearingComponent.h
  GlitchUE/Source/GlitchUE/Public/Components/HearingTriggerComponent.h
  GlitchUE/Source/GlitchUE/Public/GlitchZones/CatalyseurZone.h
  GlitchUE/Source/GlitchUE/Public/Player/UI/Tchat/Tchat.h
Labels: Bug fix, Programmation

#212 Remove collision + add missing skysphere
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/Onborading_Moving_MED_Celling.uasset
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/Onborading_Moving_MED_Floor_Tiled.uasset
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/Onborading_Moving_MED_Floor_Wood.uasset
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/Onborading_Moving_MED_Wall_LV0.uasset
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/Onborading_Moving_MED_Wall_LV1.uasset
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/Onborading_Moving_TECH_Celling.uasset
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/Onborading_Moving_TECH_Floor.uasset
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/Onborading_Moving_TECH_Wall.uasset
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/Onborading_Moving_Tiled_Wall_LV2.uasset
  GlitchUE/Content/Meshs/SkySphere/M_SkySphereReflect.uasset
  GlitchUE/Content/Meshs/SkySphere/SM_SkySphere.uasset
Labels: Bug fix

#224 Material mesh onboarding
  GlitchUE/Content/Meshs/LVL_Parts/Onboarding/Moving/SM_Onboarding_Moving_TECH_Wall.uasset
Labels: Bug fix, Update, Art

#230 VCA's + fiw materials
  GlitchUE/Content/FMOD/Desktop/Master.bank
  GlitchUE/Content/FMOD/Desktop/Master.strings.bank
  GlitchUE/Content/FMOD/Desktop/SFX.bank
  GlitchUE/Content/FMOD/Events/SFX/SFX_door_close.uasset
  GlitchUE/Content/FMOD/Events/SFX/SFX_door_open.uasset
  GlitchUE/Content/FMOD/Events/SFX/SFX_drone_deactivation.uasset
  GlitchUE/Content/FMOD/Events/SFX/SFX_ivan_speak.uasset
  GlitchUE/Content/FMOD/Events/SFX/SFX_traps_fire.uasset
  GlitchUE/Content/FMOD/PrivateIntegrationData/AssetLookup.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/M_Tech_Props.uasset
  GlitchUE/Content/Meshs/Materials/ModularKit/Pillars/M_Tech_Pillars.uasset
Labels: Update, Art, Audio

#231 Gold Generation fx
  GlitchUE/Content/VFX/Particles/FX_Avatar/Pk_LoseGold.uasset
  GlitchUE/Content/VFX/Particles/FX_Environment/Pk_GoldGeneration.uasset
  GlitchUE/Content/VFX/Particles/Meshes/SM_GoldIngot.uasset
  GlitchUE/Content/VFX/Particles/Textures/T_Key_D.uasset
Labels: Bug fix, New Feature, Art

#233 Gold_Ingot + Up_Door_Frame
  GlitchUE/Content/Meshs/ModuilarKit/Door/Up_Door_Frame_1.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Door/Up_Door_Frame_2.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Door/Up_Door_Frame_3.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Door/Up_Door_Frame_4.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Door/Up_Door_Frame_5.uasset
  GlitchUE/Content/Meshs/ModuilarKit/Door/Up_Door_Frame_Tech.uasset
  GlitchUE/Content/VFX/Particles/Meshes/SM_GoldIngot.uasset
Labels: Update, Art
